### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by gao-qs** [HongxinXiang/ImageMol#1]
Dear author:
   I am very interested in the new molecular representation you proposed, but there is something wrong when I download the pre-trained model. Could you please provide a more general github URL containing the training data and the pre-trained model. Thank you.

**Comment by pykao** [comment]
@gao-qs are you able to build the environment?

**Comment by pykao** [comment]
Hey @gao-qs 

use  `gdown --id 1wQfby8JIhgo3DxPvFeHXPc14wS-b4KB5`
