### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by SoodabehGhaffari** [HongxinXiang/ImageMol#14]
Hello,
I would like to double-check that I used the right pre-trained model. Is the model in the link below the complete and updated model?

gdown --id 1wQfby8JIhgo3DxPvFeHXPc14wS-b4KB5

I tried to generate pre-train model myself, however, when I run the code below, only around 4 million smiles converted to images. Is this what it is supposed to be?
python ./data_process/smiles2img_pretrain.py --dataroot ./datasets/pretraining/ --dataset data

I appreciate it if you help me to run Imagemol on my dataset.

**Comment by HongxinXiang** [comment]
If you use the pre-trained files we provide, approximately ~10 million images will be generated. If only 4 million images are generated, check if your program is interrupting abnormally.

**Comment by SoodabehGhaffari** [comment]
Thank you for the response.
Can I use the model in this link " gdown --id 1wQfby8JIhgo3DxPvFeHXPc14wS-b4KB5" without pretraining the model?

**Comment by HongxinXiang** [comment]
Yes, of course.

**Comment by SoodabehGhaffari** [comment]
thank you!
