### ISSUE TITLE
The mismatch in the number of classes of output dimension of the jigsaw puzzle prediction task

### ISSUE THREAD

**Issue by ldkien-304** [HongxinXiang/ImageMol#18]
![Screen Shot 2024-06-23 at 6 27 50 PM](https://github.com/HongxinXiang/ImageMol/assets/138236643/80475c17-8d13-437c-84c1-09de961c44b8)
The paper describes 100 classes, corresponding to 100 permutations. However, Figure S3 in the Supplementary Materials shows 101 classes. This appears to be a discrepancy. 

Could you clarify it ?. Thank you so much.

**Comment by HongxinXiang** [comment]
In the original paper, the permutation indices range from 0 to 100, note that there are 101 in total.
