### ISSUE TITLE
where is your pre-train model?

### ISSUE THREAD

**Issue by songyu2022** [HongxinXiang/ImageMol#2]
Dear author;
        Thanks for your works. i am very interesting in this model. so i download pre-train model that you supplied. but when i download it totally i finded there was no model file in it, it conclude data only. Do you forget upload?

**Comment by pykao** [comment]
@songyu2022 are you able to build the environment?

**Comment by pykao** [comment]
hey @songyu2022 

use `gdown --id 1wQfby8JIhgo3DxPvFeHXPc14wS-b4KB5`
