### ISSUE TITLE
IndexError for getting labels

### ISSUE THREAD

**Issue by ddayzzz** [HongxinXiang/ImageMol#3]
Thanks for this great work! When I run the pretrain code, I encounter this exception:
```
original_label2_var = torch.autograd.Variable(original_label[1].cuda())
IndexError: index 1 is out of bounds for dimension 0 with size 1
```
at https://github.com/HongxinXiang/ImageMol/blob/3b7d35d8281854fa238d54545f8689e65324ca11/pretrain.py#L300
Dataloader will generator data with an extra batch-axis at dim 0: 
![image](https://user-images.githubusercontent.com/22568844/206703283-c2d448da-7ab7-4670-b68b-79577346a36b.png)
I think the following mght fix up this issue.
![image](https://user-images.githubusercontent.com/22568844/206703718-df884e72-11eb-4fd1-be4b-8a3af5cab9e3.png)
Is it correct?

**Comment by pykao** [comment]
@ddayzzz  are you able to build the environment?

**Comment by ddayzzz** [comment]
> @ddayzzz are you able to build the environment?

I am sorry. I solved this issue by using the environment you provide. Thank you for reply.
