### ISSUE TITLE
feature extraction script?

### ISSUE THREAD

**Issue by pykao** [HongxinXiang/ImageMol#5]
Hi @HongxinXiang ,

Great job! Your method and results are pretty impressive and amazing. Do you have the script of feature extraction?

Best,
PYK

**Comment by HongxinXiang** [comment]
Hi, sorry to see it so late.
If you want to extract features, you just need to add the following line to the model definition:
`model = torch.nn.Sequential(*list(model.children())[:-1])`

**Comment by pykao** [comment]
@HongxinXiang  Thank you for your help :)
