### ISSUE TITLE
关于MPP下游任务实验结果的复现

### ISSUE THREAD

**Issue by MrsW6** [HongxinXiang/ImageMol#8]
学长你好，使用您预训练好的模型在下游任务跑的时候，即使我进行了超参数的搜索，也很难达到您论文中的结果，我不知道我的哪里出现了问题，我知道您提供了微调模型，但是我还是想请教您下游任务上的具体参数，谢谢！

**Comment by HongxinXiang** [comment]
Sorry for the late reply. 
I logged several specific hyperparameters of mpp datasets for your reference:
1. SIDER: batch=16, lr=0.03, epoch=10
2. TOXCAST: batch=64, lr=0.5, epoch=20
3. FreeSolv: batch=16, lr=0.0005,epoch=20
4. Lipo: batch=8, lr=0.001, epoch=30

Hope it helps you.
