### ISSUE TITLE
ImportError: cannot import name 'parallel_info' from 'torch.config'

### ISSUE THREAD

**Issue by Zainab-ik** [HongxinXiang/ImageMol#9]
Hi authors, 
I'm very interested in this model and I'm trying to install it on my system. 
However, I've gotten to the PyTorch installation and I keep getting an error showing

> Using cached torch_cluster-1.6.0.tar.gz (43 kB)
> Preparing metadata (setup.py) ... error
> error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully.
> │ exit code: 1
> ╰─> [6 lines of output]
> Traceback (most recent call last):
> File "", line 36, in
> File "", line 34, in
> File "/tmp/pip-install-m6s5wd8n/torch-cluster_c5c4961158204cfc86d0996e50312235/setup.py", line 10, in
> from torch.config import parallel_info
> ImportError: cannot import name 'parallel_info' from 'torch.config' (/home/zainab_ik/miniconda3/envs/imagemol/lib/python3.7/site-packages/torch/config.py)
> [end of output]

I'd love your input on it.
@pykao @HongxinXiang

**Comment by pykao** [comment]
I think you can use the environment file I provided to build your conda virtual environment.

**Comment by Zainab-ik** [comment]
Thank you
